name = "cf-check-proxyip"  # 你的 Worker 名称
main = "index.js"  # 入口文件，默认是 index.js
compatibility_date = "2026-04-07"  # 设置兼容日期为去年同一天

[env.production]
workers_dev = true  # 开发模式下使用 workers_dev，生产模式可以更改为自定义域
route = "cf-check-proxyip.7723dadie.workers.dev/*"  # 部署的 Worker 路径
account_id = "5769086c99be083c06457a3e098d3dba"  # 你的 Cloudflare 账号 ID
zone_id = "201c47403f2679403634e8157a25003c"  # 你的 Cloudflare Zone ID

